.github/workflows/deployment.yaml, .gitignore, Dockerfile, docker-compose.yaml
Added deployment setup using docker compose loading configuration from env file. Executed when newly commit pushed into the main and tagged for release.
=> feat: deployment setup

deliveries/handlers/truck_type_handler.go, deliveries/routes/route.go, repositories/truck_type/truck_type_repository.go, server.go, services/truck_type/truck_type_service.go, services/truck_type/truck_type_service_interface.go
Endpoint can be hit by accessing
`GET` `/api/truck_types`
a successful response would be look like this
=> feat: truck type list endpoint

repositories/user/user_repository.go, repositories/user/user_repository_interface.go, services/user/user_services_interface.go
=> Find user repository

repositories/order/order_repository.go, repositories/order/order_repository_interface.go, server.go
Positive test case. Factory can be run on `server.go`
```go
orderRepository := orderRepository.NewOrderRepository(db)
order, _ := orderRepository.Store(entities.Order{
DriverID: 0,
CustomerID: 1,
TruckTypeID: 1,
OrderPicture: "https://source.unsplash.com/600x600/?cargo",
TotalVolume: 889,
TotalWeight: 250,
Distance: 17,
EstimatedPrice: 290000,
Status: "REQUESTED",
Description: "Computer Components kargo weighting 250 Kilograms",
}, entities.Destination{
DestinationStartProvince: "JAWA TIMUR",
DestinationStartCity: "MALANG",
DestinationStartDistrict: "GONDANGLEGI",
DestinationStartAddress: "Jl. Mawar 07/02, Dsn. Baran, Putat Lor",
DestinationStartPostal: "65174",
DestinationStartLat: "-8.153344546086648",
DestinationStartLong: "112.64428662931326",
DestinationEndProvince: "Jawa Timur", …
```
=> feat: repository order implementation

repositories/order/order_repository.go, repositories/order/order_repository_interface.go
Test code: 
```go
orderRepo := orderRepository.NewOrderRepository(db)
order, _ := orderRepo.FindFirst([]map[string]string{
{ "field": "driver_id", "operator": "=", "value": "0" },
})
fmt.Println(utils.JsonEncode(order))
```
=> feat: find first repository

deliveries/handlers/customer_handler.go, deliveries/middlewares/jwt.go, deliveries/routes/route.go, entities/auth.go, entities/user.go, repositories/user/user_repository.go, repositories/user/user_repository_interface.go, services/auth/auth_service.go, services/user/user_services.go, services/user/user_services_interface.go
=> Edit delete customer

deliveries/handlers/admin_handler.go, deliveries/handlers/driver_handler.go, deliveries/routes/route.go, entities/user.go, repositories/region/region_repository.go, repositories/user/user_repository.go, repositories/user/user_repository_interface.go, server.go, services/user/user_services.go, services/user/user_services_interface.go
=> Edit delete driver

entities/user.go, services/auth/auth_service.go
=> fix: adjust driver respon and copier in auth services

deliveries/handlers/order_handler.go, deliveries/helpers/response.go, deliveries/routes/route.go, repositories/order/order_repository.go, repositories/order/order_repository_interface.go, server.go, services/order/order_service.go, services/order/order_service_interface.go, services/user/user_services.go, services/user/user_services_interface.go
Endpoints:
- `GET` `/api/customers/orders`  - login using customer account
query param available: 
- `status=REQUESTED,CONFIRMED,MANIFESTED` _(can be multiple status separated by comma)_
- `GET` `/api/customers/orders/{orderID}`  - login using customer account
Will return error if order doesn't belong to authenticated user
=> feat: customer list & detail order

entities/order.go, server.go, services/order/order_service.go, services/order/order_service_interface.go
Get history tracking of a spesific order details
Factory service testing
```go
// Create Log history on order 11
order, _ := orderHistoryRepository.Create(11, "Order has been confirmed", "customer")
fmt.Println(utils.JsonEncode(order))
// Show histories on order 11
histories, _ := orderService.FindAllHistory(11, []map[string]interface{}{})
fmt.Println(utils.JsonEncode(histories))
```
=> feat: service findall order history

deliveries/handlers/customer_handler.go, deliveries/routes/route.go, server.go
Endpoint: `GET` `/api/customers/orders/{orderID}/histories`
=> feat: customer detail order tracking histories

deliveries/validations/order_validation.go, entities/order.go, services/order/order_service.go, services/order/order_service_interface.go
Create order by customer.
Factory provider testing
```go
order, _ := orderService.Create(entities.CustomerCreateOrderRequest{
DestinationStartProvince: "JAWA TIMUR",
DestinationStartCity: "MALANG",
DestinationStartDistrict: "GONDANGLEGI",
DestinationStartAddress: "Jl. Mawar 07/02, Dsn. Baran, Putat Lor",
DestinationStartPostal: "65174",
DestinationStartLat: "-8.153344546086648",
DestinationStartLong: "112.64428662931326",
DestinationEndProvince: "Jawa Timur",
DestinationEndCity: "Singosari",
DestinationEndDistrict: "Pagentan",
DestinationEndAddress: "Jl. Raya Singosari No.1, Losari, Pagentan, Kec. Singosari, Kabupaten Malang, Jawa Timur 65153",
DestinationEndPostal: "65153",
DestinationEndLat: "-7.891057651435192",
DestinationEndLong: "112.66806898515588",
TruckTypeID: 1,
TotalVolume: …
```
=> feat: service order create

deliveries/handlers/customer_handler.go, deliveries/helpers/response.go, deliveries/routes/route.go, deliveries/validations/order_validation.go, services/order/order_service.go
Feature so that customer can create order. 
details: https://app.swaggerhub.com/apis-docs/wildanie12/Bringee-API/v1.0#/Customer/post_api_customers_orders__orderID_
endpoint `POST` `/api/customers/orders`
_Success_
_Validation_
=> feat: customer create order

deliveries/handlers/auth_handler.go, deliveries/handlers/customer_handler.go, deliveries/handlers/driver_handler.go, deliveries/helpers/response.go, deliveries/routes/route.go, deliveries/validations/user_validation.go, repositories/user/user_repository.go, server.go, services/auth/auth_service.go, services/user/user_services.go
point yg perlu diperhatikan:
1. saat regist driver akan mengembalikan token string kosong karena klo langsung create token maka logic account status ngga sesuai
2.  silahkeun mencoba worst case tiap endpoint :), insyaallah error messagenya dah baik
=> fix: refactor error mesaage

apispec.yaml, deliveries/handlers/customer_handler.go, deliveries/handlers/driver_handler.go, deliveries/handlers/order_handler.go, deliveries/routes/route.go, repositories/order/order_repository.go, server.go, services/order/order_service.go
- Endpoint `GET` `/api/drivers/orders`
List order yang tersedia oleh driver berdasarkan jenis kendaraan pengiriman yang dimiliki.
query param tersedia : `sortVolume=1` `sortWeight=1` `sortDistance=1`
_success_
_empty result_
_unauthorized (non driver account)_
- endpoint `GET` `/api/drivers/current_order`
Order yang sedang diantarkan oleh driver. bersifat data tunggal
_success_
_empty result_
_unauthorized (non driver account)_
=> feat: driver available orders and current on process order

deliveries/handlers/admin_handler.go, deliveries/routes/route.go, services/order/order_service.go
- endpoint `GET` `/api/orders`
Mendapatkan semua list order berdasarkan beberapa parameter filter tertentu dan fitur pengurutan data
query param tersedia: `sortVolume=1` `sortWeight=1` `sortDistance=1` `truck_type=87` `status=MANIFESTED,CONFIRMED,ON_PROCESS`
- endpoint `GET` `/api/orders/{orderID}`
=> feat: admin list and detail order

deliveries/handlers/admin_handler.go, deliveries/helpers/helper.go, deliveries/routes/route.go, repositories/user/user_repository.go, services/user/user_services.go
=> Find user v2

deliveries/handlers/admin_handler.go, deliveries/routes/route.go, services/user/user_services.go, services/user/user_services_interface.go
worst case if account has been verified:
if success:
=> Confirm driver account

deliveries/handlers/customer_handler.go, deliveries/routes/route.go, services/order/order_service.go
perubahan service:
1. Ketika admin set fixed price, status order berubah jadi "CUSTOMER CONFIRM"
2. Menambah beberapa kondisi ketika admin ingin konfirmasi order dan ketika customer ingin konfirmasi sebuah order
=> Cust confirm cancel order

deliveries/handlers/admin_handler.go, deliveries/routes/route.go, services/user/user_services.go
=> List customer

deliveries/handlers/driver_handler.go, deliveries/routes/route.go, services/order/order_service.go
=> Driver list finished orders

apispec.yaml, deliveries/handlers/admin_handler.go, deliveries/routes/route.go, server.go, services/order/order_service.go, services/order/order_service_interface.go, services/truck_type/truck_type_service.go, services/truck_type/truck_type_service_interface.go, services/user/user_services.go, services/user/user_services_interface.go
1. Untuk count driver bisa menggunakan filter status, account status dan truck type id
2. Untuk  count order bisa menggunakan filter status dan truck type id
3. Count customer dan truck tidak menggunakan filter apapun
=> Statistik data

go.mod, go.sum, repositories/truck_type/truck_type_repository_mock.go, services/truck_type/truck_type_service_test.go
Truck Type Service query unit testing,
can be run with 
```
go test ./services/truck_type -v
```
=> test: truck type query unit testing

repositories/payment/midtrans_payment_repository.go, services/order/order_service.go
Saya menambahkan implementasi action saat terjadi on cancel, expire dan deny dari pihak layanan pihak ketiga gerbang pembayaran.
=> fix: payment webhook on cancel, expire and deny

repositories/distance_matrix/distance_matrix_repository_mock.go, repositories/order/order_repository_mock.go, repositories/order_history/order_history_repository_mock.go, repositories/payment/payment_repository_mock.go, repositories/region/region_repository_mock.go, repositories/truck_type/truck_type_repository_mock.go, repositories/user/user_repository_mock.go
Provide mock repositories for unit testing involving all repositories including `distance_matrix` `order` `order_history` `payment` `region ` `truck_type` and `user` (driver & customer)
=> add: mock repositories and data collection
